### ISSUE TITLE
Compile warning in Figwheel - manifold-cljs.deferred.default contains a reserved keyword

### ISSUE THREAD

**Issue by aengelberg** [dm3/manifold-cljs#1]
![image](https://cloud.githubusercontent.com/assets/4122172/24430836/7fea19bc-13cd-11e7-999c-1f04ba7ee67d.png)

ClojureScript version 1.9.293
Figwheel version 0.5.8

**Comment by dm3** [comment]
Thanks, I saw this error but kind of let it go. I guess the right thing would be to change the namespace to something which isn't reserved, like `default_impl`.
