### ISSUE TITLE
ex/next-tick-executor is missing

### ISSUE THREAD

**Issue by akond** [dm3/manifold-cljs#3]
`(ns manifold-cljs.deferred` refers to `ex/next-tick-executor`, but there isn't one.

**Comment by akond** [comment]
Wrong call.

**Comment by akond** [comment]
i'm getting this error
```
executor.cljs:24 Uncaught TypeError: process.nextTick is not a function
    at Object.manifold_cljs$executor$Executor$execute$arity$2 (executor.cljs:24)
    at manifold_cljs$executor$execute (executor.cljs:6)
    at core.cljs:13
```
in both ff and chromium, because they have `process`, but there is no such a method in it.

**Comment by dm3** [comment]
Hm, looks like something changed with the way `node?` function detects whether javascript is running in Node vs a browser environment. See https://github.com/dm3/manifold-cljs/blob/master/src/manifold_cljs/executor.cljs#L23. This is probably related to changes in CLJS - I haven't touched Manifold-Cljs in a very long time.

Would be great if you could check what's the appropriate way to detect Node/Browser target in the current version of Cljs.

**Comment by akond** [comment]
i believe it is a shim that gets in the way.

**Comment by p-himik** [comment]
~~`node?` needs to change. `*target*` was removed quite some time ago: https://github.com/clojure/clojurescript/blob/master/changes.md#changes-26~~

Sorry for the noise. It's defined in a different way, but it still can be used just as `cljs.core/*target*`.

**Comment by akond** [comment]
ok, i used `[manifold-cljs "0.1.7-0"]` when it should have been `[manifold-cljs "0.1.7-1"]`.
README file needs some updating.

**Comment by dm3** [comment]
updated
